[bar.default]
position = "bottom"
workspace-scroll = true
layout = [
    "start",
    "workspaces",
    "wintray",
]

[component.workspaces]
type = "workspaces"
show-all = true
format = "{name}"

[component.start]
type = "image"
src = "assets/start.png"

[component.wintray]
type = "container"
halign = "end"
layout = [
    "clock",
]

[component.clock]
type = "clock"
timestamp = "%H:%M %p"
