# default config example

theme = "theme.css"
scroll_workspace = true

[bar.left]
monitor = 0
position = "bottom"
layout = [ "logo", "workspaces", "mode", "title", "box1" ]

[bar.right]
monitor = 1
position = "bottom"
layout = [ "workspaces", "mode", "title", "box1" ]

[component.title]
type = "i3window"
halign = "center"

[component.workspaces]
type = "i3workspace"
show_all = false
show_name = true

[component.mode]
type = "i3mode"
class = "gradient"

[component.logo]
type = "image"
src = "windows_black.png"
class = "gradient"

[component.box1]
type = "container"
# direction = "row"
# spacing = 5
layout = [ "box1_top", "box1_bottom" ]
halign = "end"
class = "gradient"
# valign = "end"

[component.box1_top]
type = "container"
layout = [ "cpu_icon", "cpu", "network_icon", "network"]
halign = "end"
[component.box1_bottom]
type = "container"
layout = [ "clock_icon", "clock"]
halign = "end"

[component.network_icon]
type = "image"
src = "./svg/flame.svg"
class = "icon"

[component.clock_icon]
type = "image"
src = "./svg/clock.svg"
class = "icon"

[component.cpu_icon]
type = "image"
src = "./svg/pulse.svg"
class = "icon"

# pulse - cpu
# plug
# cloud-download
# coud-upload

[component.network]
type = "network"
# interface = "enp3s0"
interface = "wlp58s0"

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"
