# default config example

theme = "theme.css"

[bar.left]
monitor = 0
position = "top"
layout = [ "icon" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "box1" ]

[component.box1]
type = "container"
direction = "column"
spacing = 10
layout = [ "clock1", "clock2" ]

[component.icon]
type = "image"
src = "icon.svg"

[component.clock1]
type = "clock"
format = "%Y-%m-%d %H:%M"

[component.clock2]
type = "clock"
format = "%H:%M:%S"
