# default config example

theme = "theme.css"

[bar.left]
monitor = 0
position = "top"
layout = [ "icon", "workspaces", "title", "box1" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "workspaces", "title", "box1" ]

[component.box1]
type = "container"
# direction = "row"
spacing = 5
layout = [ "network", "clock" ]
halign = "end"
# valign = "end"

[component.title]
type = "i3window"
halign = "center"

[component.workspaces]
type = "i3workspace"
show_all = false
show_name = true

[component.icon]
type = "image"
src = "icon.svg"

[component.network]
type = "network"
# halign = "top"
interface = "enp3s0"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M"
