# default config example

theme = "theme.css"

[bar.left]
monitor = 0
position = "top"
layout = [ "icon", "workspaces", "title", "box1" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "workspaces", "title", "box1" ]

[component.box1]
type = "container"
# direction = "row"
spacing = 5
layout = [ "network", "clock" ]
halign = "end"
# valign = "end"

[component.title]
type = "i3window"
halign = "center"

[component.workspaces]
type = "i3workspace"
show_all = false
show_name = true

[component.icon]
type = "image"
src = "icon.svg"

[component.network]
type = "network"
# halign = "top"
interface = "enp3s0"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M"
# WorkspaceEventInfo {
#     change: Focus,
#     current: Some(
#         Node {
#             focus: [
#                 94572264718160,
#                 94572264517072
#             ],
#             nodes: [
#                 Node {
#                     focus: [],
#                     nodes: [],
#                     floating_nodes: [],
#                     id: 94572264517072,
#                     name: Some(
#                         "i3ipc::reply::Workspace - Rust - Firefox Nightly"
#                     ),
#                     nodetype: Con,
#                     border: None,
#                     current_border_width: 0,
#                     layout: SplitH,
#                     percent: Some(
#                         0.7000000000000002
#                     ),
#                     rect: (
#                         6,
#                         37,
#                         1334,
#                         1010
#                     ),
#                     window_rect: (
#                         0,
#                         0,
#                         1334,
#                         1010
#                     ),
#                     deco_rect: (
#                         0,
#                         0,
#                         0,
#                         0
#                     ),
#                     geometry: (
#                         6,
#                         6,
#                         1334,
#                         1041
#                     ),
#                     window: Some(
#                         37748739
#                     ),
#                     urgent: false,
#                     focused: false
#                 },
#                 Node {
#                     focus: [
#                         94572264520400
#                     ],
#                     nodes: [
#                         Node {
#                             focus: [],
#                             nodes: [],
#                             floating_nodes: [],
#                             id: 94572264520400,
#                             name: Some(
#                                 "termite"
#                             ),
#                             nodetype: Con,
#                             border: None,
#                             current_border_width: 0,
#                             layout: SplitH,
#                             percent: Some(
#                                 1.0
#                             ),
#                             rect: (
#                                 1350,
#                                 37,
#                                 564,
#                                 1010
#                             ),
#                             window_rect: (
#                                 0,
#                                 0,
#                                 564,
#                                 1010
#                             ),
#                             deco_rect: (
#                                 0,
#                                 0,
#                                 0,
#                                 0
#                             ),
#                             geometry: (
#                                 0,
#                                 0,
#                                 737,
#                                 434
#                             ),
#                             window: Some(
#                                 65011715
#                             ),
#                             urgent: false,
#                             focused: true
#                         }
#                     ],
#                     floating_nodes: [],
#                     id: 94572264718160,
#                     name: None,
#                     nodetype: Con,
#                     border: None,
#                     current_border_width: -1,
#                     layout: SplitV,
#                     percent: Some(
#                         0.29999999999999993
#                     ),
#                     rect: (
#                         1345,
#                         31,
#                         575,
#                         1022
#                     ),
#                     window_rect: (
#                         0,
#                         0,
#                         0,
#                         0
#                     ),
#                     deco_rect: (
#                         0,
#                         0,
#                         0,
#                         0
#                     ),
#                     geometry: (
#                         0,
#                         0,
#                         0,
#                         0
#                     ),
#                     window: None,
#                     urgent: false,
#                     focused: false
#                 }
#             ],
#             floating_nodes: [],
#             id: 94572264516576,
#             name: Some(
#                 "1: browser"
#             ),
#             nodetype: Workspace,
#             border: None,
#             current_border_width: -1,
#             layout: SplitH,
#             percent: Some(
#                 1.0
#             ),
#             rect: (
#                 0,
#                 31,
#                 1920,
#                 1022
#             ),
#             window_rect: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             deco_rect: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             geometry: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             window: None,
#             urgent: false,
#             focused: false
#         }
#     ),
#     old: Some(
#         Node {
#             focus: [
#                 94572264491840
#             ],
#             nodes: [
#                 Node {
#                     focus: [],
#                     nodes: [],
#                     floating_nodes: [],
#                     id: 94572264491840,
#                     name: Some(
#                         "i3workspace.rs (~/dev/cakeybar/src/components) - GVIM"
#                     ),
#                     nodetype: Con,
#                     border: None,
#                     current_border_width: 0,
#                     layout: SplitH,
#                     percent: Some(
#                         1.0
#                     ),
#                     rect: (
#                         1920,
#                         31,
#                         1920,
#                         1022
#                     ),
#                     window_rect: (
#                         0,
#                         0,
#                         1920,
#                         1022
#                     ),
#                     deco_rect: (
#                         0,
#                         0,
#                         0,
#                         0
#                     ),
#                     geometry: (
#                         0,
#                         0,
#                         724,
#                         436
#                     ),
#                     window: Some(
#                         46137347
#                     ),
#                     urgent: false,
#                     focused: false
#                 }
#             ],
#             floating_nodes: [],
#             id: 94572264491344,
#             name: Some(
#                 "2: vim"
#             ),
#             nodetype: Workspace,
#             border: None,
#             current_border_width: -1,
#             layout: SplitH,
#             percent: Some(
#                 0.5
#             ),
#             rect: (
#                 1920,
#                 31,
#                 1920,
#                 1022
#             ),
#             window_rect: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             deco_rect: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             geometry: (
#                 0,
#                 0,
#                 0,
#                 0
#             ),
#             window: None,
#             urgent: false,
#             focused: false
#         }
#     )
# }
