# default config example

theme = "theme.css"

[bar.left]
monitor = 0
position = "top"
layout = [ "box1" ]
# inherit

[bar.right]
monitor = 1
postiion = "top"
layout = [ "clock" ]

[component.box1]
type = "container"
direction = "row"
layout = [ "clock", "icon" ]

[component.icon]
type = "image"
src = "icon.svg"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"
