# default config example

theme = "theme.css"

[bar.left]
monitor = 0
position = "top"
layout = [ "icon", "clock1" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "clock2" ]

[component.box1]
type = "container"
direction = "row"
layout = [ "clock1", "icon" ]

[component.icon]
type = "image"
src = "icon.svg"

[component.clock1]
type = "clock"
format = "%Y-%m-%d %H:%M"

[component.clock2]
type = "clock"
format = "%H:%M:%S"
