[package]
name = "cakeybar"
version = "0.3.0"

[dependencies.gtk]
version = "^0"
features = ["v3_22"]

[dependencies.xcb]
version = "0.8.2"
features = [ "thread" ]

[dependencies]
glib = "^0"
gio = "^0"
gdk = "^0"
cairo-rs = "^0"
libc = "0.2"
gdk-sys = "^0"
glib-sys = "^0"
i3ipc = "0.8.2"
chrono = "0.4"
clap = "2.31.2"
toml = "0.4"
nom = "4"
ansi_term = "0.11"
pulse-simple = { git = "https://github.com/astro/rust-pulse-simple" }
dft = "0.5.5"
notify = "4.0.0"

# stats
systemstat = "0.1.3"
probes = "0.1.3"
sysinfo = "0.5.6"

# tray
crossbeam-channel = "0.2"

[profile.release]
lto = true
