[package]
name = "cakeybar"
version = "0.1.0"
authors = ["kirjavascript <snkenjoi@gmail.com>"]

[dependencies]
chrono = "0.4"
glib = "^0"
gio = "^0"
gdk = "^0"
gtk = "^0"
gdk-sys = "^0"
clap = "2.31.2"
toml = "0.4"
i3ipc = "0.8.2"
ansi_term = "0.11"
futures = "0.1"
parallel-event-emitter = "0.2.4"

# stats
systemstat = "0.1.2"
probes = "0.1.3"
sysinfo = "0.5.6"

# tray
chan = "0.1.18"
chan-signal = "0.1.6"
bincode = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
[dependencies.xcb]
version = "0.8.2"
features = [ "thread" ]
