[package]
name = "cakeybar"
version = "0.1.0"
authors = ["kirjavascript <snkenjoi@gmail.com>"]

[dependencies]
chrono = "0.4"
glib = "^0"
gio = "^0"
gdk = "^0"
# gdk-pixbuf = "^0"
# gtk-sys = "0.6.0"
gtk = "^0"
clap = "2.31.2"
toml = "0.4"
# pango = "^0"
# cairo-rs = { version = "^0", features = ["png"] }
i3ipc = "0.8.2"

# stats
systemstat = "0.1.2"
probes = "0.1.3"
sysinfo = "0.5.6"

# tray
chan = "0.1.18"
chan-signal = "0.1.6"
[dependencies.xcb]
version = "0.8.2"
features = [ "thread" ]
