[package]
name = "cakeybar"
version = "0.1.0"

[dependencies.gtk]
version = "^0"
features = ["v3_22"]

[dependencies.xcb]
version = "0.8.2"
features = [ "thread" ]

[dependencies]
glib = "^0"
gio = "^0"
gdk = "^0"
cairo-rs = "^0"
libc = "0.2"
gdk-sys = "^0"
i3ipc = "0.8.2"
chrono = "0.4"
clap = "2.31.2"
toml = "0.4"
ansi_term = "0.11"
pulse-simple = { git = "https://github.com/astro/rust-pulse-simple" }
dft = "0.5.5"

# stats
systemstat = "0.1.2"
probes = "0.1.3"
sysinfo = "0.5.6"

# tray
chan = "0.1.18"
chan-signal = "0.1.6"
bincode = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
