# bars

[bar.left]
monitor = 0
position = "bottom"
layout = [ "workspaces", "eq", "title", "clock" ]
workspace-scroll = true

[bar.right]
monitor = 1
position = "bottom"
layout = [ "workspaces", "mode", "title", "tray" ]
workspace-scroll = true

# tray

[component.tray]
type = "tray"
icon-size = 20
halign = "end"

# clock

[component.clock]
type = "clock"
halign = "end"

# eq

[component.eq]
type = "equalizer"

# wm stuff

[component.title]
type = "window"
fixed = true

[component.workspaces]
type = "workspaces"
show-all = false

[component.mode]
type = "mode"
