theme = "theme.css"

# bars

[bar.left]
monitor = 0
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "tray", "box1" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "box1" ]

# used for scrolling workspaces only
[bar.right_scroll]
monitor = 0
position = "bottom"
[bar.left_scroll]
monitor = 1
position = "bottom"

# tray

[component.tray]
type = "tray"
background_color = "#FF0000"
icon_size = 20
halign = "end"

# menu

[component.menu]
type = "menu"
# label = "start"
window_id = "menu_popup"
items = [
    ["run termite",
        "termite"],
    ["forest bg",
        "feh --bg-fill /home/thom/backgrounds/forest.png --bg-fill /home/thom/backgrounds/mac.jpg"],
    ["mountain bg",
        "feh --bg-fill /home/thom/backgrounds/white.png"],
]

# layout

[component.box1]
type = "container"
# direction = "row"
# spacing = 5
layout = [ "cpu", "cpu_icon", "bandwidth", "bw_icon", "ip", "ip_icon", "clock", "clock_icon"]
halign = "end"
class = "gradient"
# valign = "end"

# i3 stuff
[component.title]
type = "i3window"
halign = "center"

[component.workspaces]
type = "i3workspace"
show_all = false
show_name = false

[component.mode]
type = "i3mode"

# stats

[component.ip]
type = "ip"
interface = "enp3s0" # remove this for 'auto' mode
# ipv6 = true

[component.bandwidth]
type = "bandwidth"
interface = "enp3s0"

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"

# icons

[component.cpu_icon]
type = "image"
src = "./icons/cpu.svg"
class = "icon"

[component.bw_icon]
type = "image"
src = "./icons/bandwidth.svg"
class = "icon"

[component.ip_icon]
type = "image"
src = "./icons/ip.svg"
class = "icon"

[component.clock_icon]
type = "image"
src = "./icons/clock.svg"
class = "icon"
