theme = "theme.css"
scroll_workspace = true

# bars

[bar.left]
monitor = 0
position = "top"
layout = [ "workspaces", "mode", "title", "box1" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "workspaces", "mode", "title", "box1" ]

# used for scrolling workspaces only
[bar.right_scroll]
monitor = 0
position = "bottom"
[bar.left_scroll]
monitor = 1
position = "bottom"

# layout

[component.box1]
type = "container"
# direction = "row"
# spacing = 5
layout = [ "cpu", "cpu_icon", "bandwidth", "bw_icon", "ip", "ip_icon", "clock", "clock_icon"]
halign = "end"
class = "gradient"
# valign = "end"

# i3 stuff

[component.title]
type = "i3window"
halign = "center"

[component.workspaces]
type = "i3workspace"
show_all = false
show_name = false

[component.mode]
type = "i3mode"
class = "gradient"

# stats

[component.ip]
type = "ip"
interface = "enp3s0" # remove this for 'auto' mode
# ipv6 = true

[component.bandwidth]
type = "bandwidth"
interface = "enp3s0"
# ipv6 = true

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"

# icons

[component.cpu_icon]
type = "image"
src = "./icons/cpu.svg"
class = "icon"

[component.bw_icon]
type = "image"
src = "./icons/bandwidth.svg"
class = "icon"

[component.ip_icon]
type = "image"
src = "./icons/ip.svg"
class = "icon"

[component.clock_icon]
type = "image"
src = "./icons/clock.svg"
class = "icon"
