theme = "theme.css"

# bars

[bar.left]
monitor = 0
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "box1", "tray" ]

[bar.right]
monitor = 1
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "box1" ]

# creates a 1px bar at the bottom - used for scrolling workspaces only
[bar.right-scroll]
monitor = 0
position = "bottom"
workspace-scroll = true
[bar.left-scroll]
monitor = 1
position = "bottom"
workspace-scroll = true

# tray

[component.tray]
type = "tray"
icon-size = 20

# menu

[component.menu]
type = "dropdown"
# label = "start"
window-id = "menu_popup"
items = [
    { label = "run termite", command = "termite" },
    { label = "hello", command = "echo \"hello\"" },
    { label = "pcmanfm", command = "pcmanfm" },
    { label = "terminal apps", children = [
        { label = "pipes", command = "termite -e \"pipes\"" },
        { label = "neofetch", command = "termite -e \"neofetch\"" },
        { label = "cmatrix", command = "termite -e \"cmatrix\"" },
        { label = "doge", command = "termite -e \"doge\"" },
        { label = "nyancat", command = "termite -e \"nyancat\"" },
        { label = "weather", command = "termite -e \"curl -s wttr.in/Manchester\"" },
        { label = "nonsense", command = "termite -e \"genact\"" },
    ] },
    { label = "change background", children = [
        { label = "forest bg", command = "feh --bg-fill \"/home/thom/backgrounds/forest.png\" --bg-fill \"/home/thom/backgrounds/mac.jpg\"" },
        { label = "mountain bg", command = "feh --bg-fill /home/thom/backgrounds/white.png" },
    ] },
]

# wm stuff

[component.title]
type = "window"
fixed = true
# format = '''
#     <span fgcolor="#0A83FD">«</span> {title} <span fgcolor="#0A83FD">»</span>
# '''
format = '''
    « {title} »
'''

[component.workspaces]
type = "workspaces"
show-all = false

[component.mode]
type = "mode"

# layout

[component.box1]
type = "container"
layout = [
    "battery",
    # "memory",
    "cpu",
    "cpu-icon",
    "bandwidth",
    "bw-icon",
    "disk",
    "disk-icon",
    "ip",
    "ip-icon",
    "clock",
    "clock-icon",
]
halign = "end"
class = "gradient"
# valign = "end"

# stats
[component.memory]
type = "memory"

[component.disk]
type = "disk"
mounts = ["/"]

[component.battery]
type = "battery"
battery = "BAT0"
adapter = "AC"

[component.ip]
type = "ip"
interfaces = ["enp3s0", "wlp58s0", "eth0"]

[component.bandwidth]
type = "bandwidth"
interfaces = ["enp3s0", "wlp58s0", "eth0"]
# interface = "enp3s0"

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"

# icons

[component.cpu-icon]
type = "image"
src = "./icons/cpu.svg"
class = "icon"

[component.disk-icon]
type = "image"
src = "./icons/disk.svg"
class = "icon"

[component.bw-icon]
type = "image"
src = "./icons/bandwidth.svg"
class = "icon"

[component.ip-icon]
type = "image"
src = "./icons/ip.svg"
class = "icon"

[component.clock-icon]
type = "image"
src = "./icons/clock.svg"
class = "icon"
