theme = "theme.css"

# bars

[bar.left]
monitor = 0
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "box1", "tray" ]
scroll_workspace = false

[bar.right]
monitor = 1
position = "top"
layout = [ "menu", "workspaces", "mode", "title", "box1" ]
scroll_workspace = false

# creates a 1px bar at the bottom - used for scrolling workspaces only
[bar.right_scroll]
monitor = 0
position = "bottom"
[bar.left_scroll]
monitor = 1
position = "bottom"

# tray

[component.tray]
type = "tray"
icon_size = 20

# menu

[component.menu]
type = "dropdown"
# label = "start"
window_id = "menu_popup"
items = [
    { label = "run termite", command = "termite" },
    { label = "hello", command = "echo \"hello\"" },
    { label = "terminal apps", children = [
        { label = "pipes", command = "termite -e \"pipes\"" },
        { label = "neofetch", command = "termite -e \"neofetch\"" },
        { label = "cmatrix", command = "termite -e \"cmatrix\"" },
        { label = "doge", command = "termite -e \"doge\"" },
        { label = "nyancat", command = "termite -e \"nyancat\"" },
        { label = "weather", command = "termite -e \"curl -s wttr.in/Manchester\"" },
        { label = "nonsense", command = "termite -e \"genact\"" },
    ] },
    { label = "change background", children = [
        { label = "forest bg", command = "feh --bg-fill /home/thom/backgrounds/forest.png --bg-fill /home/thom/backgrounds/mac.jpg" },
        { label = "mountain bg", command = "feh --bg-fill /home/thom/backgrounds/white.png" },
    ] },
]

# layout

[component.box1]
type = "container"
# direction = "row"
# spacing = 5
layout = [ "battery", "cpu", "cpu_icon", "bandwidth", "bw_icon", "ip", "ip_icon", "clock", "clock_icon"]
halign = "end"
class = "gradient"
# valign = "end"

# wm stuff

[component.title]
type = "window"
# fixed = [ 0.5, 0.5 ]
halign = "center"

[component.workspaces]
type = "workspaces"
show_all = false
show_name = false

[component.mode]
type = "mode"

# stats

[component.battery]
type = "battery"
battery = "BAT0"
adapter = "AC"
# ls -1 /sys/class/power_supply/ for device list (from polybar docs)

[component.ip]
type = "ip"
interface = "wlp58s0"
# ipv6 = true

[component.bandwidth]
type = "bandwidth"
# interface = "enp3s0"
interface = "wlp58s0"

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"

# icons

[component.cpu_icon]
type = "image"
src = "./icons/cpu.svg"
class = "icon"

[component.bw_icon]
type = "image"
src = "./icons/bandwidth.svg"
class = "icon"

[component.ip_icon]
type = "image"
src = "./icons/ip.svg"
class = "icon"

[component.clock_icon]
type = "image"
src = "./icons/clock.svg"
class = "icon"
