theme = "theme.css"

# bars

[bar.left]
monitor = 0
position = "bottom"
layout = [ "logo", "workspaces", "tray", "mode", "title", "box1" ]
workspace-scroll = true

[bar.right]
monitor = 1
position = "bottom"
layout = [ "workspaces", "mode", "title", "box1" ]
workspace-scroll = true

# logo

[component.logo]
type = "image"
src = "windows_black.png"
class = "gradient"

# layout

[component.box1]
type = "container"
# direction = "row"
# spacing = 5
layout = [ "box1_top", "box1_bottom" ]
halign = "end"
class = "gradient"
# valign = "end"

[component.box1_top]
type = "container"
layout = ["circuit_icon", "cpu", "pulse_icon", "bandwidth", "fire_icon", "ip"]
halign = "end"
[component.box1_bottom]
type = "container"
layout = [ "clock_icon", "clock"]
halign = "end"

# wm stuff

[component.title]
type = "window"
halign = "center"

[component.workspaces]
type = "workspaces"
show-all = true
format = "{name}"

[component.mode]
type = "mode"
class = "gradient"

# tray

[component.tray]
type = "tray"
background_color = "#221122"
icon_size = 20

# stats

[component.ip]
type = "ip"
interfaces = ["enp3s0"]

[component.bandwidth]
type = "bandwidth"
interface = "enp3s0" # remove this for 'auto' mode

[component.cpu]
type = "cpu"

[component.clock]
type = "clock"

# icons

# TODO: convert to background images

[component.fire_icon]
type = "image"
src = "./svg/flame.svg"
class = "icon"

[component.clock_icon]
type = "image"
src = "./svg/clock.svg"
class = "icon"

[component.pulse_icon]
type = "image"
src = "./svg/pulse.svg"
class = "icon"

[component.circuit_icon]
type = "image"
src = "./svg/circuit-board.svg"
class = "icon"

# database
# directory
# gear
#code
